package enums;

public enum EducacaoEspecial {
    ALTAS_HABILIDADES_SUPERDOTACAO,
    CEGUEIRA,
    DEFICIENCIA_AUDITIVA_LEVE_OU_MODERADA,
    DEFICIENCIA_AUDITIVA_SEVERA_OU_PROFUNDA,
    DEFICIENCIA_AUDITIVA_PROCESSAMENTO_CENTRAL,
    DEFICIENCIA_VISUAL_BAIXA_VISAO,
    DEFICIENCIA_FISICA_CADEIRANTE,
    DEFICIENCIA_FISICA_PARALISIA_CEREBRAL,
    DEFICIENCIA_FISICA_PARAPLEGIA_OU_MONOPLEGA,
    DEFICIENCIA_FISICA_OUTROS,
    DISFEMIA_GAGUEIRA,
    DEFICIENCIA_INTELECTUAL,
    SENSORIAL_ALTA_SENSIBILIDADE,
    SENSORIAL_BAIXA_SENSIBILIDADE,
    DEFICIENCIA_MENTAL,
    ESPECTRO_AUTISTA_NIVEL_I,
    ESPECTRO_AUTISTA_NIVEL_II,
    ESPECTRO_AUTISTA_NIVEL_III,
    ESTRABISMO,
    SURDEZ,
    SINDROME_DE_DOWN,
    TEA,
    TDAH,
    TOD;
}
