package main.enums;

public enum Auxilio {
    AUXILIO_BRASIL,
    BOLSA_FAMILIA,
    AUXILIO_EMERGENCIAL,
    BENEFICIO_PRESTACAO_CONTINUADA, 
    AUXILIO_GAS,
    AUXILIO_ALIMENTACAO,
    VALE_GAS,
    AUXILIO_TRANSPORTE,
    AUXILIO_CRECHE,
    AUXILIO_DOENCA,
    SEGURO_DESEMPREGO;
}
